---
booktitle: Proceedings of The 7th Asian Conference on Machine Learning
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
volume: 45
year: '2015'
shortname: ACML
start: 2015-11-20
end: 2015-11-22
published: 2016-02-25
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: ACML2015
month: 0
cycles: false
editor:
- given: Geoffrey
  family: Holmes
- given: Tie-Yan
  family: Liu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 7th Asian Conference on Machine Learning
    Held in Hong Kong on 20-22 November 2015

  Published as Volume 45 by the Proceedings of Machine Learning Research on 25 February 2016.

  Volume Edited by:
    Geoffrey Holmes
    Tie-Yan Liu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 20--22 Nov
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v45"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v45
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Asian Conference on Machine Learning
  url: http://acml-conf.org/2015/
  location: Hong Kong
  dates:
  - 2015-11-20
  - 2015-11-21
  - 2015-11-22
  number: 7
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
